sudo: require
language: node_js
notifications: 
  email: vinicius.vilela@jorlan.com
node_js: 
- 10.13.0
services:
- postgresql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database ts_api_test;' -U postgres
- npm i -g sequelize-cli gulp-cli
- cd server/
- sequelize db:migrate --env test
- npm install
- gulp
script:
- npm run unit-test
- npm run integration-test